version: '3.1'

services:
  dolibarr_mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: ${DOLIBARR_MYSQL_PASSWORD}
        MYSQL_DATABASE: ${DOLIBARR_MYSQL_DATABASE}

  dolibarr:
    image: tuxgasy/dolibarr
    environment:
        DOLI_DB_HOST: dolibarr_mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: ${DOLIBARR_MYSQL_PASSWORD}
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'http://0.0.0.0'
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
        - ${DOLIBARR_PORT}:80
    links:
        - dolibarr_mariadb