version: '3'
services:
  authentication:
    image: osixia/openldap:1.2.4
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    volumes:
      - ${LDAP_DATA_DIR}:/var/lib/ldap
      - ${LDAP_DATA_SLAPD}:/etc/ldap/slapd.d
    networks:
      ldap:
        aliases:
          - ${LDAP_DOMAIN}

  authentication_admin:
      image: osixia/phpldapadmin:0.7.2
      environment:
        - PHPLDAPADMIN_LDAP_HOSTS=${LDAP_DOMAIN}
      ports:
        - 6443:443
      networks:
        - ldap

networks:
  ldap:
    driver: bridge