version: '3.1'

services:
  dolibarr_mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dolibarr

  dolibarr:
    image: tuxgasy/dolibarr
    environment:
        DOLI_DB_HOST: dolibarr_mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: root
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'http://0.0.0.0'
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
        - "8081:80"
    links:
        - dolibarr_mariadb